@bearer_token = eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5MjRkN2M1ZC04ZWE2LTQxNWEtYjY2Yy0zOGVhNGY2NDA1MWQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NTI3NDI5LCJpYXQiOjE3NzQ1MjM4MjksImVtYWlsIjoiaGF3ZWhhd2hlQGpkdS51eiIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJoYXdlaGF3aGVAamR1LnV6IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiOTI0ZDdjNWQtOGVhNi00MTVhLWI2NmMtMzhlYTRmNjQwNTFkIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzQ1MjM4Mjl9XSwic2Vzc2lvbl9pZCI6Ijc2ZjkyNWFkLTc2MWEtNGI1NS05YzU0LTA3NjFkMGYzOGEzYyIsImlzX2Fub255bW91cyI6ZmFsc2V9.wN6jPh9f_NM0KixXeMYVT-kKqgkODouzmLJePpQQm9u-kQfkHo3u1ivcj0eEFd69-HFm8on2A_J8PvQvpnwK8g

###
GET http://localhost:3001/api/auth/me
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/active?shopId=925e1f3b-b646-42a7-8235-1b2c612dee94
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/history?shopId=925e1f3b-b646-42a7-8235-1b2c612dee94
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/categories
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/favourites/shops
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/favourites/services
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/reviews
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/reviews/d99964ba-11fe-4467-8107-e52ab670aa6b
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/services
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/services/89629de1-2a63-43b2-821a-e84ddf1ce1b8
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops?open=true&limit=10
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/3b8d25fe-677e-4d6b-836d-0babef7b3d80
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/services
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/reviews?limit=10&cursor=""
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/day-timeline?date=2026-03-12
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/users
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/trending/7days
Authorization: Bearer {{bearer_token}}
