@bearer_token = eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyZThhNzk1YS1mMGI2LTQ4MWQtYmIyMS02NmQ5MTQ0Y2JlM2MiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc2NTExMjc0LCJpYXQiOjE3NzY1MDc2NzQsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIyZThhNzk1YS1mMGI2LTQ4MWQtYmIyMS02NmQ5MTQ0Y2JlM2MifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc3NjUwNzY3NH1dLCJzZXNzaW9uX2lkIjoiZGIyYjA2OWQtZWVhMS00ZGZiLWJhNDQtYTM5NzgwMGNiMThhIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.9VP0hatCR87k9iHVtkOkP--6gMgqgHZZJhtc9N5an6kiaN5iuy2bZNDm8FF7XE812dG_eJVCCiukTMgsZR5UJw

GET http://localhost:3001/api/auth/me
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/users/active
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/users/history
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/available-slots?shopId=4c953f8f-f7c8-4860-962d-21a2f06bcb89&serviceId=89629de1-2a63-43b2-821a-e84ddf1ce1b8&date=2026-04-06
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/shops/4c953f8f-f7c8-4860-962d-21a2f06bcb89/active
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/bookings/shops/4c953f8f-f7c8-4860-962d-21a2f06bcb89/history
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/categories
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/favourites/shops
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/favourites/services
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/reviews
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/reviews/d99964ba-11fe-4467-8107-e52ab670aa6b
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/services?minPrice=20000&maxPrice=100000&categoryId=a85dbfa6-7c8f-4ffc-a7ad-b3a85a5503e8
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/services/89629de1-2a63-43b2-821a-e84ddf1ce1b8
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops?open=true&limit=10&minPrice=20000&maxPrice=100000&categoryId=a85dbfa6-7c8f-4ffc-a7ad-b3a85a5503e8
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/4c953f8f-f7c8-4860-962d-21a2f06bcb89
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/services
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/reviews?limit=10&cursor=""
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/4c953f8f-f7c8-4860-962d-21a2f06bcb89/day-timeline?date=2026-04-14
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/users
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/shops/trending/7days
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/services/trending/7days
Authorization: Bearer {{bearer_token}}

###
GET http://localhost:3001/api/admin/dashboard/base_info
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/analytics?type=week
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/analytics/diagram_info?type=all
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/analytics/famousServices?type=all
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/analytics/peak-hours?type=all
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/history?date=2026-04-13&search=abdu
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/services
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/staffs?search=sunna
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

###
GET http://localhost:3001/api/admin/schedule?date=all
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89