@bearer_token = eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NDI1MjM5LCJpYXQiOjE3NzQ0MjE2MzksImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc3NDQyMTYzOX1dLCJzZXNzaW9uX2lkIjoiNTFiMTJiOTctYzNjNy00YWY5LThlNDUtMDIyNjBiMjY2ZGRkIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jV9Chcfk4IGlt5wv47cNeBQpztjK5xP8_DlQnS9KVHuD0qE2XWODQaaHNHYQ0tREazFRG_JCGGcn6xhR052HWg

POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "email": "hawehawhe@jdu.uz",
  "password": "IloveMyself3",
  "name": "Abduqayumov b",
  "phoneNumber": "9930123456"
}

###
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
  "email": "hawehawhe@jdu.uz",
  "password": "IloveMyself3"
}

###
POST http://localhost:3001/api/categories
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "name": "Nail Salon",
  "icon": "palette"
}

###
POST http://localhost:3001/api/shops
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "name": "Sunnatilla electrician",
  "address": "93 Main St, Sometown",
  "phone": "+998928392363",
  "categoryId": "a85dbfa6-7c8f-4ffc-a7ad-b3a85a5503e8",
  "description": "A modern electrician with a passion for providing top-notch service and expertise. We pride ourselves on offering personalized attention and exceptional customer service. Our team is dedicated to ensuring that every customer is satisfied with their electrical needs. Whether you need help with wiring, installing new equipment, or troubleshooting technical issues, we are here to assist you. Contact us today to schedule a consultation and learn more about our services.",
  "shopImageFile": "File"
}

###
POST http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/schedule
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "dayOfWeek": 7,
  "openTime": "09:00",
  "closeTime": "18:00"
}

###
POST http://localhost:3001/api/services
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "shopId": "3b8d25fe-677e-4d6b-836d-0babef7b3d80",
  "name": "Setting a lamps",
  "price": 19.99,
  "durationMin": 60
}

###
POST http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/block
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "startTime": "2023-03-01T08:00:00Z",
  "endTime": "2023-03-01T09:00:00Z",
  "reason": "Lunch Break"
}

###
POST http://localhost:3001/api/reviews
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "shopId": "925e1f3b-b646-42a7-8235-1b2c612dee94",
  "serviceId": "74ea7c46-c05c-4be9-8726-8393919204b6",
  "rating": 5,
  "comment": "Great service!"
}

###
POST http://localhost:3001/api/favourites/shop
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "shopId": "925e1f3b-b646-42a7-8235-1b2c612dee94"
}

###
POST http://localhost:3001/api/favourites/service
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "serviceId": "74ea7c46-c05c-4be9-8726-8393919204b6"
}

###
POST http://localhost:3001/api/bookings
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "shopId": "3b8d25fe-677e-4d6b-836d-0babef7b3d80",
  "serviceId": "07abf769-24ab-455c-a2bb-6e9c252f7df0",
  "startTime": "2026-03-20T06:00:00Z"
}