POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "email": "229453m@jdu.uz",
  "password": "IloveMyself3",
  "name": "Abduqayumov Muhammad"
}

###
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
  "email": "229453m@jdu.uz",
  "password": "IloveMyself3"
}

###
POST http://localhost:3001/api/categories
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDAyMjkwLCJpYXQiOjE3Njg5OTg2OTAsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2ODk5ODY5MH1dLCJzZXNzaW9uX2lkIjoiYWFmZDUxMDgtY2EwOS00ZWI3LWIwZDYtYzg5NDczYjRhMDZjIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.BgRMUXrnyNfItRqdhFchq01I2jPCkBB3F-9T42NtBFbUOjy1h8YMLyOys_YOcpf8_X0Oux-yU3bj3Jck8mg2ug

{
  "name": "barbershop",
  "icon": "scissors"
}

###
POST http://localhost:3001/api/shops
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDAyMjkwLCJpYXQiOjE3Njg5OTg2OTAsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2ODk5ODY5MH1dLCJzZXNzaW9uX2lkIjoiYWFmZDUxMDgtY2EwOS00ZWI3LWIwZDYtYzg5NDczYjRhMDZjIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.BgRMUXrnyNfItRqdhFchq01I2jPCkBB3F-9T42NtBFbUOjy1h8YMLyOys_YOcpf8_X0Oux-yU3bj3Jck8mg2ug

{
  "name": "Muhammad Cuts",
  "address": "123 Main St, Anytown",
  "phone": "+99894101551",
  "categoryId": "dbf9cfa0-6b2d-4f61-bd0f-5f14464c8420",
  "description": "A trendy barbershop offering stylish cuts and shaves."
}

###
POST http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/schedule
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDg2MDAyLCJpYXQiOjE3NjkwODI0MDIsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4MjQwMn1dLCJzZXNzaW9uX2lkIjoiNDYxNDUyNDAtMDUwYS00MDBhLWFlYTQtMGMzYTBiYjc1YzQ5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.QOeKvaUsPaV2-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "dayOfWeek": 7,
  "openTime": "09:00",
  "closeTime": "18:00"
}

###
POST http://localhost:3001/api/services
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDg2MDAyLCJpYXQiOjE3NjkwODI0MDIsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4MjQwMn1dLCJzZXNzaW9uX2lkIjoiNDYxNDUyNDAtMDUwYS00MDBhLWFlYTQtMGMzYTBiYjc1YzQ5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.QOeKvaUsPaV2-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "shopId": "925e1f3b-b646-42a7-8235-1b2c612dee94",
  "name": "Hair cut",
  "price": 10,
  "durationMin": 30
}

###
POST http://localhost:3001/api/shops/925e1f3b-b646-42a7-8235-1b2c612dee94/block
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDg2MDAyLCJpYXQiOjE3NjkwODI0MDIsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4MjQwMn1dLCJzZXNzaW9uX2lkIjoiNDYxNDUyNDAtMDUwYS00MDBhLWFlYTQtMGMzYTBiYjc1YzQ5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.QOeKvaUsPaV2-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "startTime": "2023-03-01T08:00:00Z",
  "endTime": "2023-03-01T09:00:00Z",
  "reason": "Lunch Break"
}

###
POST http://localhost:3001/api/reviews
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDg2MDAyLCJpYXQiOjE3NjkwODI0MDIsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4MjQwMn1dLCJzZXNzaW9uX2lkIjoiNDYxNDUyNDAtMDUwYS00MDBhLWFlYTQtMGMzYTBiYjc1YzQ5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.QOeKvaUsPaV2-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "shopId": "925e1f3b-b646-42a7-8235-1b2c612dee94",
  "serviceId": "74ea7c46-c05c-4be9-8726-8393919204b6",
  "rating": 5,
  "comment": "Great service!"
}

###
POST http://localhost:3001/api/favourites/shop
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDg2MDAyLCJpYXQiOjE3NjkwODI0MDIsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4MjQwMn1dLCJzZXNzaW9uX2lkIjoiNDYxNDUyNDAtMDUwYS00MDBhLWFlYTQtMGMzYTBiYjc1YzQ5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.QOeKvaUsPaV2-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "shopId": "925e1f3b-b646-42a7-8235-1b2c612dee94"
}

###
POST http://localhost:3001/api/favourites/service
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDg2MDAyLCJpYXQiOjE3NjkwODI0MDIsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4MjQwMn1dLCJzZXNzaW9uX2lkIjoiNDYxNDUyNDAtMDUwYS00MDBhLWFlYTQtMGMzYTBiYjc1YzQ5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.QOeKvaUsPaV2-24nbEHw_i7mSSyKfKMWe0_ZGkB6dkXGPbVzGFIEWp-dU5_PdbRtkrN3INUMn-lMN7ACpqpxbw

{
  "serviceId": "74ea7c46-c05c-4be9-8726-8393919204b6"
}

###
POST http://localhost:3001/api/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY5MDkyNDY4LCJpYXQiOjE3NjkwODg4NjgsImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiMjI5NDUzbUBqZHUudXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI4ZDI5OThjMy02ZDc5LTQ5ZTgtOTAzMC1jZjEwYTU0ODc4ODYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2OTA4ODg2OH1dLCJzZXNzaW9uX2lkIjoiOWUzOTMyZDItM2M5Ny00MGQyLWI1NzMtMTQxODlkYTBkNWY2IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.hpOhKW1IFCrT03_-DWDTFKfY8XmYYFV__cS863rrCUayi14rnLBKNSEJgdwRTwmLHaZNMdylunSWVIOz_fww1g

{
  "shopId": "925e1f3b-b646-42a7-8235-1b2c612dee94",
  "serviceId": "89629de1-2a63-43b2-821a-e84ddf1ce1b8",
  "startTime": "2023-03-01T06:00:00Z"
}