@bearer_token = eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyZThhNzk1YS1mMGI2LTQ4MWQtYmIyMS02NmQ5MTQ0Y2JlM2MiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc2OTI4OTU1LCJpYXQiOjE3NzY5MjUzNTUsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIyZThhNzk1YS1mMGI2LTQ4MWQtYmIyMS02NmQ5MTQ0Y2JlM2MifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc3NjkyNTM1NX1dLCJzZXNzaW9uX2lkIjoiM2YyMGQwMjAtNTRkMi00ZWM2LWI3ODUtMDc1ZjU5ZjE3NWM5IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.tVAGgy4P9SI7o3OFpNtiT_F0BI7FkMt9PnPz4U6xvJ6fIkYcVPbnVx0u14n2vtBrUIsCUfQfj7c0SSbJZ2UROQ

###
PUT http://localhost:3001/admin/bookings/901020df-7378-49a9-bb61-b2fd44ab3641
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

{
  "status": "COMPLETED"
}
