@bearer_token = eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ5MTg3YmQ1LWY4ZGQtNGQ2YS1hNjUwLTJkYmE3YTViMzNhNiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3l4YmVpZWZneHp2YW1vZGR1dnh6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyZThhNzk1YS1mMGI2LTQ4MWQtYmIyMS02NmQ5MTQ0Y2JlM2MiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc2NDI5NTkzLCJpYXQiOjE3NzY0MjU5OTMsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIyZThhNzk1YS1mMGI2LTQ4MWQtYmIyMS02NmQ5MTQ0Y2JlM2MifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc3NjQyNTk5M31dLCJzZXNzaW9uX2lkIjoiZjAzY2E4NjYtOGUxNS00YjA0LWIxNTUtNmEzOGI5NjVjOGY2IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.3wCvqY2MOy6vH43Cf_AmRV-RnRxHksJspXh3uJ8yR5lPPNk-WaCCCaoh5gQw5jCbNPDc8qAY296aoSn91ERhcg

PUT http://localhost:3001/api/admin/services/0e037adc-5292-4f18-a7d6-30ceb2c44a59
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
x-shopId: 4c953f8f-f7c8-4860-962d-21a2f06bcb89

{
  "name": "Beard Trim", 
  "price": 5.99,
  "durationMin": 10
}

###


